http {
  base-url = "http://localhost:8181"
}

auth {
  client-id = "root"
  client-secret = "s3cr3t"
  refresh-interval-seconds = 5
}

rbac {
  enable-rbac = true
  num-principals = 5
  catalog-role-names = ["catalog_reader", "catalog_contributor"]
  principal-role-names = ["data_engineer", "data_scientist"]
}

dataset.tree {
  num-catalogs = 5

  namespace-width = 10
  namespace-depth = 5
  tables-per-namespace = 10
  views-per-namespace = 10

  columns-per-table = 10
  columns-per-view = 10

  default-base-location = "file:///tmp/polaris"

  namespace-properties = 10
  table-properties = 10
  view-properties = 10
}

workload {
  create-tree-dataset {
    table-concurrency = 10
    view-concurrency = 10
  }

  read-tree-dataset {
    table-concurrency = 5
    view-concurrency = 5
  }

  table-commits-creator {
    commits-throughput = 5
    read-throughput = 5
    duration-in-minutes = 1
  }

  read-update-tree-dataset {
    read-write-ratio = 0.9
    throughput = 10
    duration-in-minutes = 10
  }
}
