http.polaris-base-url = "http://172.30.4.231:8181"
http.dremio-base-url = "http://172.30.4.231:9047"

auth {
  dremio-type = "ppc"
  dremio-pat = "TFYJnlG0QSS2OsFj5LTdBuxwPiHqC02CTrx3K75Kc7FmeoZtpfzoEJm723Ru7w=="
}

dataset.tree {
  namespace-width = 2
  namespace-depth = 8
  tables-per-namespace = 2
  views-per-namespace = 2

  columns-per-table = 100
  columns-per-view = 100

  default-base-location = "gs://dremio-ppc/k8s-dac-20182"

  namespace-properties = 100
  table-properties = 100
  view-properties = 100

  mangle-names = true
  ppc-source-name = "gcs-ppc"
}

workload {
  create-tree-dataset {
    table-concurrency = 10
    view-concurrency = 10
  }

  read-tree-dataset {
    table-concurrency = 20
    view-concurrency = 10
  }

  table-commits-creator {
    commits-throughput = 10
    read-throughput = 10
    duration-in-minutes = 1
  }

  read-update-tree-dataset {
    read-write-ratio = 0.5
    throughput = 100
    duration-in-minutes = 5
  }

  create-tree-wiki {
    namespace-concurrency = 50
    table-concurrency = 50
    view-concurrency = 50
  }
}
