http.polaris-base-url = "http://localhost:9181/"
http.dremio-base-url =  ""

auth {
  dremio-type = "ppc2dc-without-authentication"
  dremio-org-id = "d3b8275c-fbf8-4485-9996-89258b13da3b"
  dremio-user-id = "c7b8c04d-264d-4ef7-adfe-fca6c4f6e78a"
  dremio-project-id = "38aa0da6-5839-435f-b644-e112b173cbc4"
}

dataset.tree {
  catalog-name = "serverlessproject"
  namespace-width = 2
  namespace-depth = 8
  tables-per-namespace = 2
  views-per-namespace = 2

  columns-per-table = 100
  columns-per-view = 100

  default-base-location = "s3://dcs-aws-customer-39775/catalog"

  namespace-properties = 100
  table-properties = 100
  view-properties = 100

  mangle-names = false
  ppc-source-name = "gcs-ppc"
}

workload {
  create-tree-dataset {
    table-concurrency = 10
    view-concurrency = 10
  }

  read-tree-dataset {
    table-concurrency = 20
    view-concurrency = 10
  }

  table-commits-creator {
    commits-throughput = 10
    read-throughput = 10
    duration-in-minutes = 1
  }

  read-update-tree-dataset {
    read-write-ratio = 0.5
    throughput = 100
    duration-in-minutes = 5
  }

  create-tree-wiki {
    namespace-concurrency = 50
    table-concurrency = 50
    view-concurrency = 50
  }
}
