#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Apprunner CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apprunner/**'
      - '.github/**'
  pull_request:
    paths:
      - 'apprunner/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      max-parallel: 4
      matrix:
        java-version: [21, 23]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: |
            21
            ${{ matrix.java-version != '21' && matrix.java-version || '' }}
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
        with:
          # The setup-gradle action fails, if the wrapper is not using the right version or is not present.
          # Our `gradlew` validates the integrity of the `gradle-wrapper.jar`, so it's safe to disable this.
          validate-wrappers: false

      - name: Code style checks and tests
        run: |
          cd apprunner
          ./gradlew --continue check

      - name: Check Maven publication
        run: |
          cd apprunner
          ./gradlew publishToMavenLocal

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: upload-test-artifacts-${{ matrix.java-version }}
          path: |
            **/build/reports/*
            **/build/test-results/**
